staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/jmx-gui


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 11839
# - Commit ID: 4ea7705b28134bb9f7892048b0f8a5cb6171a4b6
# - Timestamp: 2024-04-22T19:46:31Z
