staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/jmx-gui


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 3717
# - Commit ID: 90d421c329f198f15106dd30b1b0234823feafd8
# - Timestamp: 2024-09-05T20:43:47Z
